# Generated by Django 5.0.1 on 2024-01-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Short title of Role', max_length=255)),
            ],
            options={
                'db_table': 'role_group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255, null=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('nationality', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
